### ISSUE TITLE
Show CheckBoxes exception

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#137]
Hello,

If I enable Show CheckBoxes, close Testcentric and open it again by double clicking my *.dll I get an exception (attached).
[Show_CheckBoxes_Exception.txt](https://github.com/TestCentric/testcentric-gui/files/2525216/Show_CheckBoxes_Exception.txt)

Without CheckBoxes I can load the tests.

Current workaround: delete content of C:\Users\%USERNAME%\AppData\Local\NUnit\

Best regards,
Martin

**Comment by CharliePoole** [comment]
I believe this is fixed in the latest master...

**Comment by CharliePoole** [comment]
@MartinZec Closing as duplicate, but if you encounter it on the latest build, we can reopen.

**Comment by CharliePoole** [comment]
@mikkelbu I guess I should put out an alpha-2 release soon. Do you have anything you want to get in?

**Comment by mikkelbu** [comment]
@CharliePoole I think I would like to get #119 in, but I would prefer to get the other PRs merged before, so that @drSte don't have to rebase on top of mine. But if you want to get alpha-2 out then just do it. I can quite quickly redo #119 later as I just need to rerun my PS script.

Ps. As part of #119 I discovered that we have a ProjectEditor-project that is not built by cake or VS. Is it intentional that we still have this in the codebase?

**Comment by CharliePoole** [comment]
That makes sense. I also have some refactoring in process. Let's try for this week.

The project editor is there for when we need it, for example if we create an enhanced project format with projects nested in projects. I'll add an issue to track it and avoid confusion.
