### ISSUE TITLE
Redundant menu items under View | Tree

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#155]
This duplicates the functionality present in the tree itself and complicates the GUI both in terms of UX and internal implementation. The top level View | Tree menu can be completely removed. Individual menu items may be handled as follows:

__Show Checkboxes__ Already present in the Tree Context menu
__Expand__ Available from the tree control itself
__Collapse__ Available from the tree control itself
__Expand All__ Add to the Context menu
__Collapse All__ Add to the Context menu
__Hide Tests__ Add to the Context menu
__Properties...__ Already present in the Context menu

**Comment by CharliePoole** [comment]
@TestCentric/gui-team I marked this `confirm`, which is unusual for an enhancement. What I'd like is for some other team member to look at it and agree or disagree that it's a good idea. Let's see how this works as a practice.

**Comment by CharliePoole** [comment]
@mikkelbu Do you have any thoughts on this?

**Comment by mikkelbu** [comment]
@CharliePoole I have no problem with removing the top level View | Tree menu and moving the missing functionality to the Context menu.

Ps. I did some experimentation and it seems that **Collapse** in the menu is actually a **Collapse node and all sub-nodes** and not just collapsing the node as it happens when I click in the tree, but I prefer the behaviour in the tree.
