### ISSUE TITLE
Disabling Shadow Copy is Ignored

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#21]
The setting exists but it may not be used by the DomainManager service in creating the domain. Check and make it work if necessary.

**Comment by CharliePoole** [comment]
The setting is set but the engine ignores it! Either the engine needs to be fixed or we should disable the setting.

**Comment by CharliePoole** [comment]
There was temporary debug code forcing shadow copy on.

**Comment by paulens12** [comment]
I've just run into this issue and I think you might be having a regression there - or was it only ever fixed in the experimental GUI? I'm using old GUI and `Assembly.GetExecutingAssembly().Location` always returns a location in %LocalAppData% regardless of the shadow copy setting. Just verified that with latest version (1.2.0)
