### ISSUE TITLE
Console output not showing up immediately in TestCentric gui

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#320]
Running any test which has a Console.WriteLine() should write to the Text Output tab of TestCentric immediately, not wait until the Test finishes.  This is the behavior of nunit_gui.exe 2.x

This simple test will demonstrate this:

        [Test]
        public void ConsoleTest1()
        {
            Console.WriteLine("Line1");
            Thread.Sleep(5000);
            Console.WriteLine("Line2");
            Thread.Sleep(5000);
            Console.WriteLine("Line3");
        }

**Comment by CharliePoole** [comment]
@JeffKryzer This is a fundamental change in how NUnit 3 works as distinct from NUnit V2. In NUnit 3, we gained the ability to tie output to an individual test, even when tests may be running in parallel. It would usually not be useful to display that output as it appears, since it would be interrupted by other output. So most text output from a test is bundled with the XML representation of the result of that test and is only available to display at the end of the test. The GUI is displaying the output as soon as it is available.

However, NUnit 3 also provides other channels for text output. `TestContext.Progress` and `TestContext.Error` output display immediately as does any write to `Console.Error`.

**Comment by JeffKryzer** [comment]
Thanks for explaining.  Makes sense.  This is unfortunate for our company, we have years of NUnit integration tests which loop through large datasets and show progress along the way.

Note that I inserted this statement into my test and still saw nothing in the TestCentric gui:

TestContext.Progress.WriteLine("Progress1");

Would you expect that to show up somewhere?

**Comment by JeffKryzer** [comment]
Disregard.  It is working now (guess my test didn't reload).  Thanks for the tip, I guess we'll switch to that.
