### ISSUE TITLE
Stopping a long running test from TestCentric gui does not stop right away

### ISSUE THREAD

**Issue by JeffKryzer** [TestCentric/testcentric-gui#337]
If you press the Stop button when a long test is running, it doesn't stop the test right away.  It waits until that test finishes.  Only then does the Agent stop and the Run button is re-enabled.

This is different than nunit_gui 2.x which stopped the test immediately.

Note, if you close the TestCentric gui window when a long running test is running, it DOES stop and kill the agent right away as it is closing.  So that's good.

**Comment by CharliePoole** [comment]
I know this is true, but I marked confirm because I want to map out the boundaries of the problem. For example, does it only occur when running in a separate process? Or also when running in-process?

The GUI only has one button to stop the test and the engine has two modes: stop after all tests finish running and force an immediate stop. Perhaps for this GUI, we should use the immediate stop mode to be compatible with NUnit V2. Then for the next (experimental now) GUI, figure out a UI that lets the user first try to stop it cooperatively and then force it if that doesn't work. What do you think?

**Comment by CharliePoole** [comment]
BTW this may require fixing the engine. This is one of those features that is not used by other runners and so is not as well-worked-out as it could be.

**Comment by CharliePoole** [comment]
@JeffKryzer This happens the same way for all process models, just as you described.

When I temporarily change the argument to StopTestRun so it's a forced stop, the GUI hangs. So this will need some work, I fear, possibly within the engine.

**Comment by CharliePoole** [comment]
I've traced this to NUnit itself. The problem with the "non-cooperative" forced stop is that even though it doesn't require the test's cooperation, it does require that of the framework. While NUnit appears to be aborting execution correctly, it isn't notifying us that the inflight test suites have terminated.

I'm going to see if there is an easy way for us to work around this in either the GUI itself or in our build of the engine.

**Comment by CharliePoole** [comment]
PR #356 changes the GUI to use the forced termination option, which is supposed to cause the run to stop immediately. However, the NUnit 3 framework doesn't actually cancel the run and the GUI still hangs.

PR nunit/nunit#3281 fixes the framework problem and anyone who uses future builds of tne NUnit framework once this is merged will get a neat stop. However, anyone using current builds will continue to see the hang.

Consequently, I'm now looking at an additional PR to handle the framework versions that don't properly support cancellation and this issue is still open.
