### ISSUE TITLE
Unable to run selected NUnit V2 tests

### ISSUE THREAD

**Issue by Sharken03** [TestCentric/testcentric-gui#340]
Tested with TestCentric Runner for NUnit 1.0.0-Beta - April 13, 2019 installed from Chocolatey.

In a situation where you have mixed test assemblies, that is test assemblies for NUnit V2 and NUnit V3, it appears that running NUnit V2 test assemblies does not work as intended.

The primary Run button as well as the Run options from the Tests menu seems to work as intended for NUnit V3 test assemblies.

**For NUnit V2 test assemblies only "Tests -> Run All" works.**
Running selected or failed tests from the Tests menu does nothing and the Run button also does nothing.
The tests were carried out using the attached test assembly from https://github.com/nunit/nunit/issues/3231

**Comment by CharliePoole** [comment]
Is the V2 framework driver also installed from chocolatey?

**Comment by Sharken03** [comment]
On the first attempt i had used a custom V2 framework driver. It's a bit hard to tell since Testcentric does not show what folder the extension is loaded from.

On my second attempt i have used the V2 framework version 3.7.0 from https://chocolatey.org/packages/nunit-extension-nunit-v2-driver. The behavior is the same.

**Comment by CharliePoole** [comment]
@Sharken03 Using the Beta release, I'm not even able to run the v2 test alone. I tried with your provided assembly as well as with one of my own. I also duplicated the problem with the current pre-beta2 code.

When you run the v2 test alone, do you merely open it from the GUI? I've tried it that way as well as by putting it on the command-line.

This is rather hard to debug, since the engine is separate from the testcentric code. I'm thinking of extracting and using the source to build it so I can more easily step into the engine.

**Comment by CharliePoole** [comment]
I have created issues nunit/nunit-console#639 and nunit/nunit-console#640 to deal with problems in the engine that are blocking this issue. I may be able to incorporate some fixes in the private engine build I'm now using as a result of PR #353.

**Comment by CharliePoole** [comment]
The discussion about this has been in several issues and PRs, so I thought I should summarize the status of running V2 tests under the current build of the GUI. See the linked items for more detail.

1. It is not possible to run V2 tests from the GUI by selecting individual tests. That includes the Run button, the menu items (except Run All) and the context menu. That's because the GUI passes a test ID filter in when tests are selected. The V2 framework doesn't understand V3 Ids and the V2 driver extension doesn't handle it in translating V3 to V2 filters.

2. Run All will work as will selection based solely on category filters.

3. This can't be handled in the GUI very well, because we don't want the GUI to know it's running V2 rather than V3 tests - and even if we did, it's non-trivial and/or duplicative to find out.

3. It also can't readily be handled in our private build of the engine. At least not without injecting special knowledge about NUnit V2 into parts of the engine that shouldn't know about it.

4. I'd prefer not to bundle a special build of the NUnit V2 Framework driver along with my engine build, so I'm waiting for feedback from the NUnit engine team as to how they would like to see this fixed. Ideally, I'd submit a PR to them and require GUI users to upgrade to the latest V2 Framework Driver in order to run V2 tests selectively.

That's all for now folks!

**Comment by CharliePoole** [comment]
@TestCentric/gui-team As explained, this issue is really with the V2 Framework Driver, which throws an exception when it encounters an id filter. We report the exception now, but it means you get an error whenever you select any tests to run if __any__ of the assemblies uses NUnit V2. The error appears even if the test you selected was in an NUnit3 assemblie, because the filter created is used for every assembly.

It seems to me that we cannot release 1.0 with this error, unless we are willing to tell people not to use the GUI with NUnitV2 assemblies.

We could conceivably use a workaround if we knew that the assembly in question used the V2 framework. Currently, that information is not available from the engine, however, and it seems like a pretty major change to the interface to make it available.

What do you think? Is it reasonable to release with that warning to users and allow those who exclusively use NUnit 3 to take advantage of the GUI?

**Comment by immeraufdemhund** [comment]
I think it is reasonable. Especially since we know it is a problem, it is a hairy problem and we plan on doing something about it...but in the interest of getting something working out to the masses to start giving more feedback I think would be better

**Comment by mikkelbu** [comment]
I agree with Robert. Also I know that many of the people that have reported issues against the legacy project and the gui works in the same company (my old company), so I think it is better to get this release out and create some awareness about it (even with this issue).

Ps. Is there anything I can help with wrt. nunit/nunit-v2-framework-driver#29 ? (I can make an attempt at option 3, but I don't think that I have worked in the code base before).

**Comment by CharliePoole** [comment]
OK, I'll go with this and document the fact that it doesn't work. I'll move this issue to the 1.1 milestone as high priority.

@mikkelbu That would be great. I'll get you some info about this asap. Note that their are two changes... one to the nunit-legacy project and then another simpler one to the v2 framework driver. I'll create the nunitv2 issue.

**Comment by CharliePoole** [comment]
This is now working using the new build of the v2 framework driver that I created locally.

@ChrisMaddock can we figure out how to get a new release of the driver out, so I can mark this as done?

**Comment by Sharken03** [comment]
Am looking forward to give this new version a try. I do have one question, will it be possible to expand the Tools->Extensions page to show version of extensions loaded as well as where the assembly was loaded from ?

**Comment by CharliePoole** [comment]
I'll post a link to the package I'm using locally when I'm back at my computer.

I have filed an issue on the nunit console project to display versions. Makes sense here as well. Would you post an issue?

**Comment by mikkelbu** [comment]
The nuget package containing the build of master can be found at https://ci.appveyor.com/project/CharliePoole/nunit-v2-framework-driver/builds/26867025/artifacts

**Comment by CharliePoole** [comment]
That's it! Thanks @mikelbu. Since the GUI is a chocolatey package, you want nunit-extension-nunit-v2-driver. The other package, NUnit.Extension.NUnitV2Driver, is for a nuget install.

I had trouble getting the AppVeyor artifact feed to work directly, so I downloaded the package and put it in my local packages folder.

**Comment by Sharken03** [comment]
Created issue 395 above regarding version and path of loaded extensions in TestCentric GUI.

**Comment by ChrisMaddock** [comment]
@CharliePoole Created a core team discussion on a new driver release. Let's wait for people to respond there first, but in lieu of a "proper maintainer" for this project, I'd be happy to do one further release for these final fixes. (Although I'd appreciate any help, if you'd be willing!)

**Comment by CharliePoole** [comment]
@ChrisMaddock I'm getting back in the swing of things again after focusing on other stuff for some weeks. Should we look at doing a release of these fixes for the extension?

**Comment by ChrisMaddock** [comment]
Sure! Did you have any further thoughts on future maintenance of this extension, or are we likely to consider this the 'final release'?

**Comment by CharliePoole** [comment]
I'm willing to maintain it in principle, but at a pretty low level of effort with anything that smacks of "enhancement" rejected. We can let the Core Team decide if that's OK. Probably, the next step for this release is to review the existing PRs and issues and see what would be done with them. If I take a shot at that, you could review and it would give us a notion about whether we agree on the future direction of this project. Of course, it could be that anything at all is preferable to just shelving it. :smile:

**Comment by ChrisMaddock** [comment]
> I'm willing to maintain it in principle, but at a pretty low level of effort with anything that smacks of "enhancement" rejected.

This sounds ideal to me, but you're right it needs agreement from the core team.

**Comment by CharliePoole** [comment]
Release 3.8 of the NUnit V2 Framework Driver now supports an Id Filter, which is what the GUI uses to select tests. To be able to select tests from the GUI, you will need to have that version installed.

As a result, I'm closing this issue.
