### ISSUE TITLE
Assemblies Running in Parallel (Regardless of Settings)

### ISSUE THREAD

**Issue by CalvinAllen** [TestCentric/testcentric-gui#358]
In our project, we have 4 test assemblies loaded into the Test Centric runner (Beta 2, testcentric.exe) using an NUnit project loader adding, and the file.

Regardless of our settings for Domain Model or Process (explicitly setting both to Single), our assemblies are running in parallel (this does not happen when supplying the same project file to the nunit3-console.exe v3.8.0).

If we revert back to Alpha 2, the problem is not occurring (it does occur with every release from Beta 2 back to Alpha 1).

I'm at a loss as to what to look for / what to check / etc, and could use some guidance / wisdom / etc.

Thanks!

**Comment by CharliePoole** [comment]
Can you provide a copy of your project file? You can block out the names of the dlls if you need to.

When you say you have tried different settings, do you mean in the project file?

**Comment by CalvinAllen** [comment]
> When you say you have tried different settings, do you mean in the project file?
Yeah

`<NUnitProject>
  <Settings activeconfig="Debug" />
  <Config name="Debug" processModel="Single" domainUsage="Single" configfile="NUnit.config">
    <assembly path="1.dll" />
    <assembly path="2.dll" />
    <assembly path="3.dll" />
    <assembly path="4.dll" />
  </Config>
</NUnitProject>`

**Comment by CharliePoole** [comment]
Added "fences" for the formatting. Edit your post to see how I did it.

**Comment by CharliePoole** [comment]
I'll look into this but in the meantime, some suggestions...

* The domain setting has nothing to do with running in parallel. It controls whether all tests run in the same domain or separately. Setting it to Single means that all tests should run in one AppDomain. You should do that if you have a really good reason. There are not many such reasons. :-) Otherwise use the default, which runs them in separate AppDomains.

* If you use `--processModel="Multiple` or leave the setting out, then each test is run in a separate Process, which makes the domain setting moot. That's the __only__ way that the tests will run in parallel - or should do at any rate. I'll test that out to be sure.

* If you use all defaults, assemblies run in parallel unless you use `--agents=1` on the command-line. There's no equivalent in the project file. With that setting, only one project is run at a time.

Of course, the problem is no less a bug just because there are workarounds. I'll look at it.

**Comment by CharliePoole** [comment]
I've confirmed by examining the code that there could be a problem if you have a saved setting of "Multiple" in the NUnit settings file. In that case, it will be used and will always override what is in your project file. Can you check by examining your settings in the GUI settings dialog?

**Comment by CharliePoole** [comment]
This is actually related to #357 as well. That is, if there is no way to __save__ the process setting, then we should not be using it at all any longer. May even need some code to clean it out, along with any other settings that are no longer in use.

**Comment by CharliePoole** [comment]
Calling this a bug. Saved setting for ProcessModel is used (saved by some past version of the program), overriding the settings in the project file. No way is provided to change that setting, so we should be ignoring it entirely.

**Comment by CalvinAllen** [comment]
> I've confirmed by examining the code that there could be a problem if you have a saved setting of "Multiple" in the NUnit settings file. In that case, it will be used and will always override what is in your project file. Can you check by examining your settings in the GUI settings dialog?

It looks like its always set to "Default" as far as I can tell, and the NUnit settings file doesn't appear to have anything listed.

**Comment by CharliePoole** [comment]
In that case, I think your problem would go away if you could use the latest build or when the beta3 release comes out. We were overriding the project settings with Default, which obviously should not happen.

**Comment by CalvinAllen** [comment]
Sounds good, thanks @CharliePoole!
