### ISSUE TITLE
Add command line option for specifying results file location

### ISSUE THREAD

**Issue by csmack99** [TestCentric/testcentric-gui#382]
Need some type of mechanism to be able to specify not only the name of the test results xml file but also the ability to specify a path to where to store the xml file.  I think the easiest way would be a command line argument.  Or, is there a way to do it now with the latest version?

**Comment by CharliePoole** [comment]
Have you tried specifying the location when using the Save Results menu item?

**Comment by csmack99** [comment]
I am trying to make it where it automatically saves the xml file where I want it to after the run without user intervention.

**Comment by CharliePoole** [comment]
I suppose the logical thing would be to implement a `--work` option, as in the console runner. Then we would save everything relative to the work directory, which defaults to the current directory.

I like this a bit better than a `--result` option because it works equally well with a single run from the command-line using `--run` and any runs you do from the GUI. We could use the work directory as the initial starting point for the save results dialog as well.

**Comment by immeraufdemhund** [comment]
would it work too if we add said option to the nunit project file?

**Comment by CharliePoole** [comment]
@immeraufdemhund So we would be effectively saying... For this particular project, all results should be saved to a particular location? What if we ran two different projects in one run?

**Comment by immeraufdemhund** [comment]
oh I didn't know you could load multiple projects in one 😄  

Wouldn't that also be a NUnit project? and so the parent project would override the child projects?

**Comment by CharliePoole** [comment]
My thinking on projects is that the `.nunit` project belongs to The NUnit Project. :smiley: 

It's also a bit hard to conceive of how you would combine them because they require `config` entries.

OTOH a TestPackage, once expanded, has no configs but only test assemblies arranged in some sort of hierarchy for purposes of summarization and reporting. Issues #3 and #211 envision saving TestPackages so that people could re-open the last package they ran, including multiple projects and/or assembiles as well as the settings they used. IMO, this is where you would save the work directory. I put #3 in the 1.1 milestone because I think it's pretty important.

**Comment by csmack99** [comment]
> I suppose the logical thing would be to implement a `--work` option, as in the console runner. Then we would save everything relative to the work directory, which defaults to the current directory.
> 
> I like this a bit better than a `--result` option because it works equally well with a single run from the command-line using `--run` and any runs you do from the GUI. We could use the work directory as the initial starting point for the save results dialog as well.

Thank you for your quick response!  How hard would it be to make the two changes you mentioned.  The first one being adding the --work flag to the command line logic.  The second would be the ability to set a "Work Directory" with which to point where the results file would go.

Please let me know your thoughts...  Thank you.

**Comment by CharliePoole** [comment]
It wouldn't be that hard because the engine already supports the notion of a Work Directory. Would you be willing to do a PR?

**Comment by csmack99** [comment]
Sorry but I cannot do a PR

**Comment by CharliePoole** [comment]
No problem. We'll take a look at it for the next release.
