### ISSUE TITLE
Please push the testcentric-gui package to nuget.org

### ISSUE THREAD

**Issue by TFTomSun** [TestCentric/testcentric-gui#391]
I couldn't find the nuget package via nuget.org. Instead i had to download it manually. Can you please push it to nuget.org whenever a new version is released?

**Comment by CharliePoole** [comment]
We release the GUI as two packages, one zip and one for chocolatey. Although the chocolatey package is a night package, I follows chocolatey conventions and isn't suitable for nuget.off. You should install it on your dev machine using choco.exe. See the readme file for more info.

**Comment by TFTomSun** [comment]
sorry, but choco doesn't fit into the build process because it requires an additional tool that a developer might not have on his pc. nuget instead is part of msbuild, and the package can be restored during build to start debugging against the restored test centric gui

**Comment by CharliePoole** [comment]
I'm reopening this for comments by other users and, in particular, the @TestCentric/gui-team.

I'm frankly not very keen on the idea but I'll state my reasons in a separate comment.

**Comment by CharliePoole** [comment]
My thoughts...

When I set up the project, I selected chocolatey as the primary means of distribution, with a zip file as the secondary one for those with "special" needs. I think chocolatey is the ideal environment for tools that are installed and used by developers, which is what I intended TestCentric to be.

Nuget is the right place for libraries upon which any project depends. Generally, such projects reference an assembly, which is distirbuted as a package. and call into it. Different projects may require different versions and nuget support that. The alternative of requiring a central installation of each library, referenced by the individual projects is pretty unmanageable and breaks down in the face of multiple versions. This has long been accepted by most developers as the ideal use of nuget.

Tools, on the other hand, are executables. The projects do not reference them and then do not reference the projects. With rare exceptions, a single install per machine works just fine. (One exception, of course, is when one is working on or debugging the tool itself.) Further, no project actually __requires__ that a particular tool be used. If the project, for example, has NUnit tests, the developer is free to run them in a variety of ways: console runner, VS adapter, resharper, etc.

Of course, some people (generally managers) may say something like "But we __require__ the developers to run the tests using a particular tool." In my view and experience as a coach, this is an anti-pattern and one I don't particularly want to enable. This, of course, is a choice that those of us working on Open Source software are able to make. We can choose what we are willing to support. That's why I'm asking the @TestCentric/gui-team to weigh in on this.

There are also technical downsides to having projects reference the GUI. Here are a few:

1. Each dev machine ends up with multiple copies of what may be different versions of the GUI.

2. The machines on which continuous integration is performed end up installing software that is not used.

3. Assemblies have fake references to things that they do not really make use of.

4. By default, the assemblies in the referenced package are copied to the output directory.

5. In addition to the GUI package, any NUnit engine extensions that are needed must be separately installed in each project, rather than just once.

6. Because NuGet and Chocolatey nuspec files use differing conventions, somebody on the NUnit team needs to do double work in maintaining the packages so that the same features are available in both environments.

BTW, all of this also applies to installation of the NUnit console runner through a nuget package. However, in that case, the downsides are outweighed (we hope) by the fact that the console runner is actually used as part of a CI build.

**Comment by CharliePoole** [comment]
@ferventcoder I'd appreciate any comments you have on this discussion.

**Comment by TFTomSun** [comment]
there are actually very prominent tools that are distributed via nuget. please have a look at. net core, the dotnet cli and dotnet global tools. with global tools Microsoft provides i feature rich infrastructure for distributing tools via nuget. 

as i mentioned in my scenario i set the debugging settings for test projects via central targets, so that they are automatically linked to the test centric gui. this is very useful when you have remote debugging scenarios. The targets need a reliable way to ensure the presence of the test centric gui. the best way to ensure that is via nuget restore or via dotnet global tool which could be installed during the build.

**Comment by CharliePoole** [comment]
Sorry, I don't know exactly what you want to do. Are you saying you want to run the GUI remotely on your build servers?

Once we understand your use case, we'll try to figure out if we want to support it.

I should note that there is nothing to prevent you installing the package directly, using nuget rather than choco, provided you can deal with the non-standard structure of the nupkg in the code that invokes the tool.

**Comment by TFTomSun** [comment]
@CharliePoole 
Please see my edits... I tried to make it more clear.

According to your point to install the package directly. Of course I can download the package and add it to our Artifactory nuget feed manually whenenver a new version is released. Thats also what I did now. But it would be much better of course if I could directly pull it from nuget.org over the Artifactory remote repository for nuget. Then i can save that manually step whenever a new  version is released. And I can also set the package reference so that it always pulls the latest version of the test centric gui. That means the developers would automatically get the latest tool with new features and bugfixes.

**Comment by CharliePoole** [comment]
What I meant is that you can install the package normally using either chocolatey.org or our myget feed. Since you are not referencing any of the contained assemblies, but only launching the executable, you only have to know its path within the package.

That's if my interpretation of what you are trying to do is correct. 

This is degenerating into a dialog. Let's allow some other folks to express an opinion.

**Comment by CharliePoole** [comment]
@TFTomSun I can't believe you sent me basic documentation about Visual Studio! Please reconsider any plans you may have for a career in diplomacy. :smiley:

**Comment by CharliePoole** [comment]
Just on more followup question...

Is the limitation behind all this the fact that the test engine (and therefore the GUI) needs to run on the same machine as the code? If that constraint were to go away, would it change things for you?

**Comment by TFTomSun** [comment]
if the visual studio test Explorer or ReSharper Unit Testing would support remote execution, i wouldn't need the test centric gui anymore. But they don't and i don't see that support coming in the near future. 

The great nunit gui runner features are that it's a lightweight copy deployable runner. You don't even need to deploy it locally u can execute it from a network share. And that's what i am actually doing when i do remote debugging, i execute it on the test machine via network share directly from package location on the dev machine. The test assembly is also passed to the runner via network unc path (from the dev machines build output) 
Actually it makes it easier for remote debugging scenarios that the test runner and engine is in the same process, because when u start the runner ur are automatically attached to the test code, too. So I always run the tests in process without shadow copy to remote execute them via backward network connection directly from the dev machines build output in the test machine.

**Comment by TFTomSun** [comment]
Oh just saw that you mentioned a myget feed... that might be an option, but then i need to request proxying that feed. the nuget.org feed is already proxied. So why not taking the feed that everybody uses?

**Comment by CharliePoole** [comment]
Because putting a package that follows the rather different chocolatey conventions on nuget.org would be very confusing to a lot of people.

**Comment by TFTomSun** [comment]
regarding remote debugging documentation. I know that only few people use the remote debugging features of csharp projects. Most people just copy their app to the target machine, start it, and attach the debugger manually. But there are better ways... but they need some project configuration that i extracted into build packages.

**Comment by TFTomSun** [comment]
But publishing it on an unknown feed is less confusing? I am fine if the package doesn't follow the library conventions, because it's not a library. I don't rely on any convention in this scenario

**Comment by TFTomSun** [comment]
anyway i just wish i could restore it as everything else. if i need to proxy an additional feed just for this one package then it's like that. I wish it would be simpler.

**Comment by CharliePoole** [comment]
That changes what I thought you were asking for. I understood you wanted us to create a proper nuget package, which we don't currently have. If you're asking to have the existing chocolatey package placed on nuget.org that's a different matter. Is that what you're asking? (Remains to be seen whether nuget would accept it.)

**Comment by TFTomSun** [comment]
yes, exactly. That's what i am asking for. 😊

**Comment by CharliePoole** [comment]
I'm closing this as "Won't fix" for the second time. I reopened it with the thought that one of the team members might have a different view than I do but nobody has spoken in favor of the request over the past few days.

Now that I understand the request more exactly, there's an overriding reason in my mind to turn it down. NUget.org is for nuget packages. Chocolatey.org is for chocolatey packages. Even though both kinds of packages use the nuget format, they are not compatible in normal use. Someone who installs a published nuget package expects it to create a certain structure within their project. A chocolatey package doesn't do that. That's why NUnit itself has different packages for use with nuget and chocolatey, for example, NUnit.Console (nuget.org) and nunit-console-runner (chocolatey.org).

**Comment by TFTomSun** [comment]
yeah, and where's the logic behind that the console runner is a nuget package and the gui runner a chocolatey package? 😉

**Comment by CharliePoole** [comment]
I understand it's frustrating to not get what you want, but have you actually read my last comment?

The console runner has __both__ a nuget package and a __chocolatey__ package. If we felt that a nuget package for the GUI was a good idea, we would have both for the GUI as well.

Using the __same__ package for both purposes is a total non-starter. Nuget.org and chocolatey.org have quite different conventions regarding the contents of the `.nuspec` file. It took me quite a while to get both of them right for the console runner.

Having __both__ packages, on the other hand, is a possible feature even if I don't personally like it. I never liked the idea of a nuget package for the console runner, but others felt differently so we did it. That's how a volunteer project works - or should work IME.

In this case, at least so far, nobody has spoken in favor of the idea of two packages. That could always happen, I suppose, in the future, in which case we might re-open this.

**Comment by immeraufdemhund** [comment]
sorry about not throwing my two cents into the ring on this earlier. Having had setup multiple build environments for my last job I understand the difficulty of getting the build server on the same page as the developers not to mention getting the legacy apps to all work with the current build process. That said from the dev ops point of view having a script in hand that I can run with powershell script to keep all my tools at a specific version is nice using choco. And a gui runner for my automated processes doesn't seem like the right fit. I'd much rather just get the console runner with all of it's plugins to ensure compatibility. I believe that gui's are more of the responsibility of the developer to keep up to date or at a specific version. I vote for just keeping it in chocolatey.
