### ISSUE TITLE
ILogger conflict

### ISSUE THREAD

**Issue by midexsoftware** [TestCentric/testcentric-gui#506]
Hi,
I use mvvmlight and nLog in my project.  It seems that ILogger in my program conflicts with ILogger in this GUI.  My tests run fine from the VS.  Any Suggestion?

```
MyProject.Data.Test.OrdersDataServiceTest (TestFixtureSetUp):
System.InvalidOperationException : There is already a factory registered for NLog.ILogger.

at GalaSoft.MvvmLight.Ioc.SimpleIoc.Register[TClass](Func`1 factory, Boolean createInstanceImmediately) in C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight.Extras (PCL)\Ioc\SimpleIoc.cs:line 340
at AllergyCanada.Data.Test.DataServiceTestBase.InitializeAssembly() in G:\Clients\AllergyCanada\AllergyCanadaSoftware\AllergyCanada.Data.Test\DataServiceTestBase.cs:line 37
at AllergyCanada.Data.Test.OrdersDataServiceTest.<SetupLocal>d__0.MoveNext() in G:\Clients\AllergyCanada\AllergyCanadaSoftware\AllergyCanada.Data.Test\OrdersDataServiceTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 99
at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
at NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\SetUpTearDownItem.cs:line 68
at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeTestCommand.cs:line 50
at NUnit.Framework.Internal.Commands.BeforeTestCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeTestCommand.cs:line 50
at NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp() in D:\a\1\s\src\NUnitFramework\framework\Internal\Execution\CompositeWorkItem.cs:line 257
```

**Comment by CharliePoole** [comment]
While the GUI does have an ILogger interface, it's not available to the framework at all and our error is entirely within the NUnit framework.

The NUnit framework __also__ has an ILogger interface, but like the GUI it has nothing to do with NLog. Is it possible that your program is trying to access the log interface just by it's name, rather than acquiring it from NLog?

I'd say this is definitely not a GUI problem and most likely not a framework problem. My first suspicion would be the Mvvm framework you are using. That said, if you like, I can transfer this issue to the NUnit project.

**Comment by midexsoftware** [comment]
Thank you for quick reply. I use mvvmlight.  I also use nSubstitute (don't think it matter)  This is how I register my logger. Why would it work from VS using NUnitAdapter and not in GUI?
var logger = Substitute.For<ILogger>();
SimpleIoc.Default.Register<ILogger>(() => logger);

My guess was that somewhere in GUI the same interface is registered, hence it conflicts.

See it references lbugn here.  I don't have such a path on my computer.
 C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight.Extras

**Comment by CharliePoole** [comment]
I edited your example so it's legible online using GitHub Markdown "fences". Did the same for your first post as well. You should do that on GitHub issues, but especially when you have angle brackets, otherwise people can't see the code  at all.

I assume the code you posted is in your NUnit test. `NUnit.Framework.Internal.ILogger` is an NUnit interface. Without seeing your using statements, I can't tell if that's what you are registering or if it's the NLog interface.

The GUI is not "registering" any interfaces with anything. It doesn't use `MvvmLite`, `SimpleIoc` or `Nlog` at all. Further, there's nothing in the stack trace that has anything to do with the GUI - it's all inside the framework, which is entirely separate. Assuming you are running with default settings, it's happening in a separate process entirely - the GUI is merely displaying the error.

The error message seems to indicate that you have tried to register the interface twice. Can you post more complete code that shows where you are doing this? I'm wondering if it's in some bit of test code that is executed more than once by NUnit.

Regarding the adapter vs the GUI, it's not surprising that two different applications would react differently to this situation when it arises. In the case of the adapter, errors in TestFixtureSetUp are generally not easy to see without debugging, while the GUI makes them much more visible.

**Comment by midexsoftware** [comment]
I figured out the issue.  Not sure if this is intended or an issue in the GUI. Here is the problem.  I realized, when I unload and reload dll, it works first time.  Then it fails second time with an error.  So it looks like after tests are executed, GUI does not dispose the test class, hence my OneTimeSetUp is called each time when you press Play to run tests. Since I register my logger in the OneTimeSetUp class, it stays in cache.  When you run tests 2nd time, it tries to register the same logger again, hence causing the issue.  

The solution is to Reset the SimpleIoc in the OneTimeTearDown.  My sample code is bellow.  

`[TestFixture]
    public class TestClass
    {

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            ServiceLocator.SetLocatorProvider(() => SimpleIoc.Default);

            var logger = LogManager.GetCurrentClassLogger();
            SimpleIoc.Default.Register<ILogger>(() => logger);
        }

        //if you comment out this method, then after 1st run test will fail.
        [OneTimeTearDown]
        public void TearDown()
        {
            SimpleIoc.Default.Reset();
        }


        [Test]
        public void TestMethod()
        {           

            var answer = 42;
            Assert.That(answer, Is.EqualTo(42), "Some useful error message");
        }
    }`

**Comment by CharliePoole** [comment]
Yes, that's the sort of error I imagined... OneTimeSetUp is a good name in many ways (better than TestFixtureSetUp) but sometimes it's confusing - When using  a GUI users may think it's "one time for the entire session" but it's actually "one time per test execution".

That also explains the difference between the GUI and the VS adapter... in the adapter a completely new process is usually (you can change this) created each time you execute the tests. In the GUI, the same process is continued to be used.

I'm marking this as a question and closing it but if anything related comes up you can still post comments to the issue.
