### ISSUE TITLE
Update nuget and chocolatey packages

### ISSUE THREAD

**Issue by paulens12** [TestCentric/testcentric-gui#522]
nuget.org lists 1.0.1 as the newest version available, and `choco install testcentric-gui` installs version 1.1.0 even though 1.2.0 has been available for a while and isn't marked as "beta" in Github.

**Comment by CharliePoole** [comment]
I just noticed that there is no chocolatey package for 1.2.0 although I thought I had uploaded it. Could be I had a connection problem and then forgot to come back to it.

The NUget download was a surprise to me as I don't publish the GUI on nuget.org. In fact, I see the package is "owned" by someone else. I need to download and do more analysis, but at a glance it looks like it's version 1.2. In fact, it seems to be an exact copy of my chocolatey upload, which is a bit of a problem since chocolatey has its own variations on the nuget format. It even includes the file VERIFICATION.txt, which informs you that the product author and the package maintainer are the same person!

I'll need to do a bit more research on this and figure out if the package owner is violating nuget.org's terms of service. At best, he's confusing people with his versioning scheme.

**Comment by CharliePoole** [comment]
@TFTomSun Your github user id matches the nuget user id of the person publishing the above referrenced testcentric package. Are you the guy?

**Comment by CharliePoole** [comment]
Marking this critical WRT the chocolatey update.

**Comment by CharliePoole** [comment]
@paulens12 Because I had already seen a problem on chocolatey, I guess I misread your issue. What I find on chocolatey is the 1.1 gui, even though the 1.2 has been out for a while. You stated that you find 1.2 and that you believe 1.3 has been out for a while.

Could you confirm your description and, if you are thinking 1.3 is out, please let me know what leads you to say that.

**Comment by paulens12** [comment]
Oh, 1.3.0 was a typo and I only noticed it ~2h after posting this issue. Sorry for the confusion. What I meant is that the choco package is 1.1.0 while 1.2.0 is already available, just like the current version of the issue description says.

It was surprising to learn that the nuget.org package is "fake". We'll probably have to remove it from our workflow.

@CharliePoole, I have a question for you, or rather I'd like to hear your advice. Since nuget integrates directly with most build tools, we currently use the testcentric-gui package as part of our development build process, so that when any team member builds our project, they have access to a test runner GUI. This seems like an effortless way to distribute the binary to every team member without having to introduce any additional setup steps for their dev environment, and also to ensure everyone uses the same version. Do you have any suggestions for a better distribution model? If not, any thoughts on providing your own "official" nuget package? I know chocolatey is built on top of nuget, so my initial idea was to pull straight from their repository because our build tools integrate well with nuget, but I couldn't find a link to the actual underlying nuget repo for chocolatey (I don't know if that's even possible, to be fair) so I settled for the nuget.org package I found.

I also know that this is not the "nicest" way of distributing executables because nuget is primarily meant for assemblies/components, but the reason we went with it is that nuget is so universal, while chocolatey requires installing additional software on each developer's machine.

**Comment by CharliePoole** [comment]
Ah... then I had a compensating brain typo when I first read it! I'll see about uploading.

You have understood correctly the reason why I didn't use nuget, but I hadn't considered the possibility that someone else would do it! 

The advantage of chocolatey is that the GUI is then available for __any__ project the developer works on, of course. You could download the chocolatey package and use it on nuget barring any warnings that nuget.org might give for odd stuff like having the license in the tools directory rather than the root or use of the iconurl.

I'm generally inclined to leave tools up to individual developers where possible. That's why, in the past, I haven't been very responsive to arguments like "we want all our developers to use X." However, I recognize that what you are talking about can be very convenient for the developers. I'll pursue this further and see about creating an official nuget package... possibly with some text to suggest you consider the chocolatey install instead. :smile: 

One advantage of the chocolatey install is that all usage of the gui on a machine gets the same extensions. OTOH with nuget, you have to add each desired extension to the package. That could be considered a feature (different extensions per project) but I think that's a bit of a stretch, and generally, extensions can be disabled.

**Comment by paulens12** [comment]
Well the thing is we want to have a controlled way of running unit tests that works for everyone. We could just use the console runner, but passing a bunch of test names as parameters is inconvenient to say the least, and VS test runner depends too much on individual configuration (e.g. ReSharper, that some colleagues use, replaces it so it's different; also there are different versions of Visual Studio, and some people are starting to switch over to VSCode entirely). Chocolatey package is an OK solution, but some people might update their packages more often than others, so it's best to have the version of testcentric we use be tied to the exact commit that it works with, i.e. if you update the test runner, you fix tests if necessary (I know it's just a frontend, but there might be breaking changes, such as moving from nunit-agent to testcentric-agent lately...), make a commit and everyone who pulls it automatically gets a working version.

As for machine-wide configuration, usually it doesn't matter because each project has its own configuration: some use older versions of NUnit, some use alternative unit testing frameworks, some don't have any C# code at all... So each of them will have to be setup individually, including such things as test runners. The basic idea is that NUnit is treated as any other library used in any project, and testcentric just complements it. Just like you want to keep your code dependencies inside your repository or close to it (as opposed to a system-wide location), we want to keep testcentric as part of the project and not of the system.

**Comment by CharliePoole** [comment]
You're very convincing!

**Comment by CharliePoole** [comment]
OK, although @TFTomSun hasn't responded, I found this issue #391 where he argues for having a nuget.org package, so I'm guessing he went ahead and did it. Licensing allows that, although courtesy might call for telling us, since we get any issues that arise.

As noted above, there are some problems with the package and I plan to contact nuget.org about them: In summary...
* The versioning is wrong
* The package is not a "normal" nuget package but is formatted according to the chocolatey requirements.
* The package contains a text file stating that @TFTomSun is one of the authors of the GUI.

I get a certificate error when trying to contact the author via nuget.org, but he should be able to see his @mention here. Next step will be to contact nuget.org about restricting use of the Testcentric prefix to this organization, as they currently do for NUnit.* and having the package removed.

I never did understand @TFTomSun's reason for needing the package... as far as I could tell, it was to run the GUI on a CI server... but that might just be my not understanding his explanation. @paulens12 gives some pretty good reasons for a nuget package even for a developer tool and the ability of other people to release such packages and make it look as if we had done them is a convincing argument to do it ourselves, whether it's a good idea or not.

**Comment by CharliePoole** [comment]
Since I can't get to the "contact user" page on nuget.org without a certificate violation, I have gone ahead and reported the package to nuget.org support.

**Comment by TFTomSun** [comment]
@CharliePoole sorry that i didn't reply to this thread earlier. I am currently on vacation, that's why i didn't check github. But as we already discussed via email i am totally willing to handover that package to you, where it belongs to. I just uploaded the chocolatey package on nuget for similar reasons as @paulens12 wants to have it there. I even have other packages (sdks) that restore that package and point to it's content. I tried to explain my scenario in the other issue, but it got closed.

The modifications regarding the author/owner must have been done automatically during the upload ... i didn't change the content actively.

I would like to emphasize my argument to pack it as a global tool again. That would also help the guys who use vscode and prefer to use the command line to run/start tools and wouldn't change anything for all other users who want to restore it as a part of their build workflow.
see https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools for more information.

**Comment by CharliePoole** [comment]
@TFTomSun I looked at the docs and I'll look back at your original issue, in case you mentioned global tools there. That's a new feature of nuget.org to me, however, glancing at the above link, it seems to be only for .NET Core. I'll reasearch further.

Regarding ownershihp: I'm still shown as the owner in the nuspec but that doesn't allow me to do anything with it. The gallery uses it's own idea of ownership, which is apparently separate from what's in the nuspec file. Whoever uploads a new package becomes the sole owner as far as the gallery is concerned. That makes sense, of course, since otherwise you could just edit the nuspec file and make yourself the owner of somebody else's package.

Anyway, I'm starting work on this under #523 in order to keep the nuget.org update separate from the chocolatey update, which is also needed.

**Comment by TFTomSun** [comment]
@CharliePoole I'm not sure whether only. net core apps are supported. I don't see a reason why, because in the end a global tool is just a package with an executable, a redirect entry point and a path variable.

Additionally I don't see any reason why the gui runner should not be buildable against  . net core. windows forms is supported since . net core 3.0. You could build it as self cobtained app. It's see future,.net 5 is based on .net core, all the .net core concepts will be standard concepts starting with. net 5, that's why i would at least give it a try. Also every developer who has installed visual studio 2017 onwards has a .net core sdk pre-installed already.

**Comment by CharliePoole** [comment]
@TFTomSun I'll look into the global tool stuff further as soon as I clear some other stuff.

Re .NET Core... On Linux, I currently use .NET Core via the Cake tool to build the GUI, but I still target it to Mono. That will change eventually. I'm anticipating something like .NET Framework 4.8 and .NET Core App 3.1 builds for the GUI at some point.

There is other stuff that has priority, however, most notably getting .NET Core agents to run correctly. I'd really like to get all those things done and wrap up the 1.x series so I can move on to other stuff.

**Comment by CharliePoole** [comment]
The chocolatey package for 1.2 is now available, which ends work on this issue.

Issue #523 is also closed with publication of the nuget package.

I'll create additional issues for automating publication of the packages and @TFTomSun and I will work separately to see whether just delisting his package is OK or if it should be deprecated.
