### ISSUE TITLE
Debug by running agent directly

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/testcentric-gui#557]
Marking this as an Idea.

Tests can currently be easily debugged in the GUI by running them in-process. However, there are two problems:
 1. The GUI is built for .NET 4.5 and can only run tests that target the .NET Framework.
 2. We'd ideally like to get rid of in-process execution, requiring tests to always run under an agent.

Test agents use only the engine core and are built for all supported runtimes. However, they are designed to be run from and communicate back to the GUI. They don't generally function if simply run from the command-line.

However, their communication is based on arguments passed on the command-line. It should be possible to provide an argument telling the agent that it is __not__ being run by the GUI. In that case, perhaps it could simply report it's progress as console output. If that were done, then the agent could be used with an external debugger for quick debugging of a test assembly.

This will take some investigation and design.

@TFTomSun @TestCentric/gui-team @ChrisMaddock @jnm2 Your ideas and comments are welcome.

**Comment by TFTomSun** [comment]
I don't understand see any problems with in process running. 1. can be solved, as i stated in the other issue, u can easily build against a list of target frameworks in the new msbuild world. the 2nd point is not well explained... just someone wants to get rid of it... why?

The proposed solution doesn't cover my use case. I debug with the UI because i want to be able to select the tests that i want to run. I use the gui almost only for remote debugging. The UI is directly run from the restore test centric gui package that i restore together with the test. So the whole configuration is defined in code and doesn't depend on the remote machines configuration.

**Comment by CharliePoole** [comment]
Sorry, as noted on #444 I just saw this comment...

Thoughts on your idea...

Currently, the agent is passed command-line arguments to tell it how to connect to the GUI. Because the GUI launches the agent, we can be sure that those arguments are correct. .NET Framework agents connect using a remoting URL passed as an argument. .NET Core agents (not yet released) use a TCP endpoint, which is passed to them. All agents also have a guid identifier, created for them by the engine and of course they get their specific test selection filters from the gui through a remote call or tcp message. If you just started an agent directly, it would have to find a particular instance of testcentric, somehow figure out what endpoint to use and somehow identify it. It's doable, but it's a reversal of what already happens... the agent would need to give info to the GUI rather than the reverse.

Here, however, is another thought... When the engine launches agents it creates a command-line. Why can't that command-line specify a debugger running the agent? The agent would still get the same arguments and connect back directly to the engine and GUI but the debugger would be running the show. If that sounds interesting, I could show you how to try an experiment.

About the problems...

 * Once a test is running, the GUI just waits for progress messages and a final result - at least so long as you don't try to cancel the test run.

 * Loading or failing to load a test happens in the agent. So you should be able to debug most such failures. Sometimes a problem will be detected in the GUI or main engine so that we don't even try to load. Those problems are usually well reported because no remoting is involved.

What debuggers to you currently use when you execute the GUI? What does a typical command-line look like?

**Comment by CharliePoole** [comment]
Are you in a position to make your own build of the GUI and try an experiment with it?

**Comment by TFTomSun** [comment]
I have build packages that automatically create these project settings:

for local debugging:
![image](https://user-images.githubusercontent.com/5387192/78456945-2de7bf80-76a7-11ea-9471-e14d20224a91.png)


for remote debugging:
![image](https://user-images.githubusercontent.com/5387192/78456967-48ba3400-76a7-11ea-80b6-489a02a7aac8.png)

That allows me a one click solution or debugging:

- select a test project and set it as startup project
- hit F5 -> Debugging / Remote Debugging starts -> Debugger is attached to the TC GUI -> when I use inprocess, the debugger is attached to the test already

**Comment by CharliePoole** [comment]
I got that... Your approach makes it easy to use the V1 GUI in process and debug the tests. I'm trying to come up with a different approach for V2 (or let's say Vnext since we could have other major releases before it). I'm envisioning the debugger being __between__ the Gui and the agent so the GUI launches the debugger which then launches the agent. The agent would continue to communicate directly with the GUI once launched.

Are you using some internal debugger? Would it work in that environment - i.e. launched by the GUI itself? We could experiment, of course. A hard-coded spike would take a minutes rather than hours.

**Comment by TFTomSun** [comment]
I'm using the Visual Studio debugger and the Visual Studio Remote Tool (Remote Debugger). You can programmatically attach the Visual Studio Debugger to a process via the VS SDK, I think even to a remote process. But I think the  remote start of the program (in your scenario the agent) won't work. 


I have already such an implementation for ssh debugging for. net core and raspberry PI. In this implementation I have something like a debug manager which is basically the program that I start to debug. This manager deploys than the real application to the PI via ssh and attaches the VS debugger to that remote process.
On windows I wouldn't know how to deploy and start the remote process... because we don't have ssh there out of the box. Maybe someone can find out how the VS remote debugger can be triggered to do it. I didn't find any documentation for the communication protocol between VS and the Remote Debugger

**Comment by TFTomSun** [comment]
I forgot to point that out. We currently have to world's of remote debugging. The legacy world (windows only and proprietary) via the Visual Studio Remote Tools for Windows and the new world SSH based remote debugging that I currently use for Linux (Raspberry PI). For the new world I have already everything that is necessary to achieve what you want. For the legacy world, due to the proprietary protocol I don't know how i can start a process remote via directly communicating with the VS remote debugger.

**Comment by CharliePoole** [comment]
This was implemented as feature #817
