### ISSUE TITLE
InvalidCastException, "Properties" context menu entry

### ISSUE THREAD

**Issue by trivalik** [TestCentric/testcentric-gui#595]
**Describe the bug**
I load a test assembly (I found later out that it was NUnit 2 test assembly), but only one red entry in treeview appears. I right click on it and press on "Properties" and the exception appears:

System.InvalidCastException: Das Objekt des Typs "System.Boolean" kann nicht in Typ "System.String" umgewandelt werden.
   bei TestCentric.Gui.TestPropertiesDialog.FillPackageSettingsList() in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestCentric\testcentric.gui\Dialogs\TestPropertiesDialog.cs:Zeile 174.
   bei TestCentric.Gui.TestPropertiesDialog.DisplayProperties(TestSuiteTreeNode node) in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestCentric\testcentric.gui\Dialogs\TestPropertiesDialog.cs:Zeile 96.
   bei TestCentric.Gui.Presenters.TreeViewPresenter.<>c__DisplayClass10_0.<WireUpEvents>b__23() in C:\Users\charlie\dev\TestCentric\testcentric-gui\src\TestCentric\testcentric.gui\Presenters\TreeViewPresenter.cs:Zeile 261.
   bei System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.MenuItem.MenuItemData.Execute()
   bei System.Windows.Forms.Command.Invoke()
   bei System.Windows.Forms.Control.WmCommand(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**To Reproduce**
see description

**Expected behavior**
no exception

**Screenshots**
-

**Environment (please complete the following information):**
 - TestCentric Version 1.4.0
 - OS: Windows 10 1809 Enterprise
 - Target Runtime for your test assembly: .NET Framework 4.8

**Comment by CharliePoole** [comment]
What is the exact version of the NUnit framework being here?

**Comment by trivalik** [comment]
Test test assembly I load was build against NUnit 2.6.3. This was my fault. but anyway.

**Comment by CharliePoole** [comment]
And do you have the V2 Framework Driver installed with the GUI? That is, you would need to have installed it in the same way you installed the GUI - i.e. nuget or chocolatey.

**Comment by trivalik** [comment]
No, I just downloaded the release here, without nuget, chocolatey. In VS2019 is the NUnit 2 Test Adapter installed. I downloaded via browser the nuget package on chocolatery and same.

**Comment by CharliePoole** [comment]
@trivalik Yes, but you can find three packages here:

* TestCentric.GuiRunner.1.4.0.nupkg (the nuget package)
* testcentric-gui.1.4.0.nupkg (the chocolatey package)
* testcentric-gui-1.4.0.zip (the zip package)

You would use nuget.exe to install the nuget package, choco.exe to install the chocolatey package.

This is important because testcentric will only find and use extensions installed by the same method, whether nuget or chocolatey. If you install the zip package, there is no automatic ability to find extensions. You must set them up manually.

Testcentric makes no use of the VS test adapter, which is used by Test Explorer.

If you need more details, just tell me which testcentric package you are using and how you install it. I'll then tell you how to install the V2 Framework driver.

**Comment by CharliePoole** [comment]
I found the bug, which is not related to problems with NUnit V2, so you can ignore the previous comment unless you run into further problems running V2.

**Comment by CharliePoole** [comment]
The exception is fixed in master so I have closed this issue. But if you continue to have problems running V2 tests, feel free to comment further and I'll answer.
