### ISSUE TITLE
Add Getting Started section to the documentation

### ISSUE THREAD

**Issue by JasonNewellAtAllegro** [TestCentric/testcentric-gui#603]
I installed the latest version, 1.41 from within Visual Studio.
Now I want to launch the GUI. 
Where is the documentation that tells me how to do this? I've read about chocolatey and zip files. Doesn't help me.
You guys obviously have way too much knowledge on all of this but coming to it cold a few breadcrumbs to find the way to start the GUI would be useful.

**Comment by CharliePoole** [comment]
Have you looked at the documentation in the GitHub project wiki? They're at https://github.com/TestCentric/testcentric-gui/wiki

If there's anything not clear in the docs, let me know. That way we can try to improve them.

**Comment by JasonNewellAtAllegro** [comment]
Yeah, at some length and I couldn't find a thing that told me how to start the GUI which is why I went to the effort of creating a GitHub account and raising this as an issue.
I had to do a search of my PC to find where it was located. In C:\users\jnewell\.nuget I found all the installed packages and there was a testcentric.guirunner folder in there. My companies antivirus tool then removed the testcentric.exe but that's another story. If you think logically about the next step after first time installation, this is the bit you are missing. The wiki deals with installation then skips directly to the GUI features.

**Comment by CharliePoole** [comment]
The Command-Line page tells how to use it from the command-line, but it only works when using the preferred install from chocolatey.org unless the user adds the install directory to path manually. So that needs revision.

Can you tell me precisely how you went about installing so I can make sure your use case is covered? I'm a bit confused how it ended up in the .nuget directory.

**Comment by JasonNewellAtAllegro** [comment]
Yeah, I raised another ticket this morning actually before reading this. I think that will explain what I was doing. The package failed to install from within Visual Studio #604 so I downloaded the zip file which incidentally has been left with the nuget file type (I'm not raising an issue over that but it makes your installation documentation confusing). I had to rename the file extension then extract it and I put it to where Visual Studio was trying to place it because I didn't know where it was supposed to go, its not clear from the documentation how you would expect it to be used. I think some examples would help in the documentation on setups. I know that you cannot anticipate every permutation of use case.

**Comment by CharliePoole** [comment]
Quick answer for now as I'm in meetings today and tomorrow.

Your error seems to be that you don't have access to the directory in which the package is being installed. Check that.

Unclear why you want to install TC into Visual Studio. It's nut used in VS but from the command-line. If your company environment allows it, install chocolatey and use the chocolatey package. That way you'll have TC for use with every project.

**Comment by CharliePoole** [comment]
Re-reading this, I noted the comment that the zip file was left with the nuget file type, which got me thinking.

In fact, there is no zip file, as I noted in a new issue, #613. That's a bug for sure.

I think you must have used the `testcentric-gui-1.4.1.nupkg` file. Of course, it is in zip format because all `.nupkg` files are formatted as zip files. The different files are intended for different purposes...

 * `TestCentric.GuiRunner-1.4.1.nupkg` is used for installing locally with `nuget.exe` as a part of your project. You may also simply install it from `nuget.org`.
 * `testcentric-gui-1.4.1.nupkg` is used for installing locally with `choco.exe`. You may also simply install it from chocolatey.org, which is the approach we recommend.

If you want the gui to be part of your project, so that all developers have it available, then installing TestCentric.GuiRunner from within Visual Studio is your best approach. If you simply want to use the gui yourself, on your own machine, then I strongly recommend downloading choco.exe and using that to install the `testcentric-gui` package. That "just works" - the program is added to your path and you only have to type it's name.

All that said, you've uncovered a number of things that should be improved in the documentation, so I'll keep this open.

**Comment by CharliePoole** [comment]
NOTE: the zip has been added to the 1.4.1 release for anyone who needs it.

**Comment by CharliePoole** [comment]
I re-titled this issue to reflect what I think is needed based on this discussion.

The Getting Started Section should include Installation, Execution, Running tests, Stopping the Run and Reviewing Results at a minimum. As part of Installation, the purpose of each of the downloads and how to choose the one to use should be explained.

**Comment by JasonNewellAtAllegro** [comment]
The GUI is part of a project and I want the team to use it but I found out more information.
Visual Studio creates a cache of the different packages and this where the original problem occurred. The package ends up being part of the project but if the cache can't be created the installation within Visual Studio fails. I'm going to be creating my own nuget packages for Allegro binaries so I will soon understand this process better.

**Comment by CharliePoole** [comment]
I've decided  to include a longer of the different types of installation and particularly why I don't recommend using NuGet for the GUI, even though it's very useful for other kinds of things. Should be available in a few days...

**Comment by CharliePoole** [comment]
As noted above, this should not be closed since it's tracking changes to the documentation.
