### ISSUE TITLE
Testcentric 1.5.2: About testcentric throws an unhandled exception

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#638]
TestCentric 1.5.2 GUI: Help -> About TestCentric... triggers this issue.
I think I saw it also at 1.5.1.

Also the extensions and settings have the same issue.

![error](https://user-images.githubusercontent.com/44475413/102795072-93521c80-43ac-11eb-90eb-ac085a43a31a.png)

**Comment by CharliePoole** [comment]
Turns out some other dialogs are affected as well: Test Parameters, Test Properties.

This is a pretty common issue about accessing resources with a new wrinkle due to the new project format. It turns out that the old format was more tolerant of classes in the "wrong" namespace, i.e. not matching the  Default + any nested folder structure. For example, all of the `TestCentric.GuiRunner.dll` Dialogs were in the `TestCentric.Gui` namespace but were stored in a `Dialogs` subfolder. We just need to be more rigorous about this in the future.

There's also a more general question about how this got past our CI build. Seems like we are not testing actual initialization of the dialogs. Since the bug is critical, that will be a matter for a follow-up issue.

**Comment by CharliePoole** [comment]
@MartinZec This is merged into master and available on our MyGet feed as 1.5.3-dev-00025. Are you able to take it for a test drive? If it looks OK, I'll release 1.5.3 now.

**Comment by MartinZec** [comment]
@CharliePoole I installed 1.5.3-dev-00025, the reported issue is fixed in this version (1_5_3.png).

 A minor graphical remark : on the 1.5.3 menu I see additional dashes where at the versions before a grayed out line has been shown (see menu*.png).

![menu_1_5_2](https://user-images.githubusercontent.com/44475413/102987982-8865cc00-4513-11eb-93a4-10acd134bf6c.png)
![menu_1_5_3](https://user-images.githubusercontent.com/44475413/102987987-8996f900-4513-11eb-813a-6196b4243fd4.png)
![1_5_3](https://user-images.githubusercontent.com/44475413/102987989-8a2f8f80-4513-11eb-8fe4-bc51eeafda15.png)

**Comment by CharliePoole** [comment]
@MartinZec Thanks for checking it out. I know the reason for the dashes. It's an outcome of #635. I'll fix that in the release.
