### ISSUE TITLE
Unable to load Nunit V2 assembly compiled with .net framework 4

### ISSUE THREAD

**Issue by MahendraChoudhary** [TestCentric/testcentric-gui#663]
**Describe the bug**
Unable to load Nunit V2 based test dll in the testcentric with V2 framework driver if test dll is compiled with .net framework 4.8

**To Reproduce**
1.Create Nunit v2 test library with .net fw 4.8
2. Compile the project.
3. Load dll in test-centric 1.6
4. Test centric shows error icon in the project tree and result says not test found.

**Expected behavior**
Testcentric should support .Net 4.0 runtime.
Same dll running fine with Nunit-Console 3.11

**Environment (please complete the following information):**
 - TestCentric Version: 1.6.0
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.8

**Comment by MahendraChoudhary** [comment]
![image](https://user-images.githubusercontent.com/16460793/104753342-dae68100-577d-11eb-978b-5d4efa8f4f88.png)

**Comment by CharliePoole** [comment]
@MahendraChoudhary Need a  bit more info...

* How was the GUI installed (NuGet, Chocolatey, Zip)?
* Same question for the V2 Framework Driver
* In case you used the Zips, show me the directory structure where you unzipped both of them
* Are you using defaults for ProjectModel and DomainUsage or changing them?
* Can you check that your test assembly had a TargetFrameworkAttribute added? (Use ILDasm)

The last question is because the GUI assumes .NET 2.0 if it doesn't find the attribute. If you don't find it, then let me know exactly how you compile your test assembly and what compiler you use.

**Comment by MahendraChoudhary** [comment]
-  How was the GUI installed (NuGet, Chocolatey, Zip)?
   It was installed via Nuget.
-  Same question for the V2 Framework Driver.
   Also Nuget
-  In case you used the Zips, show me the directory structure where you unzipped both of them
   Please refer below images.
![image](https://user-images.githubusercontent.com/16460793/104816865-d08eba80-5843-11eb-9921-792eec848c1c.png)

![image](https://user-images.githubusercontent.com/16460793/104816889-05027680-5844-11eb-8f30-443cd806d91b.png)


-  Are you using defaults for ProjectModel and DomainUsage or changing them?
   Using Defaults
-  Can you check that your test assembly had a TargetFrameworkAttribute added? (Use ILDasm)
  Yes, it does have.

![image](https://user-images.githubusercontent.com/16460793/104817104-33cd1c80-5845-11eb-82a2-f7a99da75bca.png)

**Comment by CharliePoole** [comment]
Thanks for all the info! I'm still a bit confused about the installation...

You said you used nuget, but you also showed a dump of what appears to be a download of the testcentric-gui source code. Did you install the nuget version or did you build from source?

**Comment by MahendraChoudhary** [comment]
> Thanks for all the info! I'm still a bit confused about the installation...
> 
> You said you used nuget, but you also showed a dump of what appears to be a download of the testcentric-gui source code. Did you install the nuget version or did you build from source?

I have downloaded package (https://www.nuget.org/packages/TestCentric.GuiRunner/) and performed unzip.

**Comment by CharliePoole** [comment]
The packages (both the runner and the extensions) are designed to be installed by nuget.exe, not by unzipping them. Of course, it's possible to unzip them, since the `.nupkg` file is basically a zip file but you then have to use knowledge of how the packages work to put them in the right place.

The important thing is the relative path from the runner directory to the directory with the extension. Can you show me how the two are located in relation to one another after installation?

**Comment by CharliePoole** [comment]
@MahendraChoudhary Your errors strongly suggest that the V2 Framework Driver is not properly installed. Although you indicate you installed both from nuget.org, the dump of the file contents is not consistent with that, as it contains an `addins` directory, which is not part of the package. You should not attempt to install packages by downloading them and manually adjusting the contents unless you have a very deep understanding of how NUnit works internally. Installing both packages using `nuget.exe` will put them in the proper relation to one another so that everything "just works."

Since you haven't responded further for over 60 days I'm closing this issue. But if you have further comments or questions, you can continue to post to this issue and I'll respond.
