### ISSUE TITLE
Test centric working directory remains TC binaries instead of loaded assembly path

### ISSUE THREAD

**Issue by gps7** [TestCentric/testcentric-gui#924]
**Describe the bug**
We have quite few tests which after upgrade from Nunit 2 to Test Centric is failing due the file not found. Usually, we have in the C# solution additional files like settings.xml which are copied to the output directory on build (file property "Copy to Output Directory" set to "Copy Always").
Then during one time setup of the test fixture this file is loaded using path ".\SubFolderName\settings.xml". This always worked with older version of Nunit and this works with console Nunit 3 on build server but does not work with Test Centric GUI.

Loading files using fallowing command: _System.IO.File.ReadAllText(".\SubFolderName\settings.xml");_

Exception observed:
```
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
```

**To Reproduce**
1. Open C# solution. Create folder "Test". Create new item in this folder like "myFile.xml".
2. Select this file and in the properties set to Copy always on build action.
3. In same solution/project create unit test and write test case: Assert.That(System.IO.File.Exist(".\Test\myFile.xml"), Is.True);
4. Build solution (ensure that bin folder contains subfolder "Test" and xml file inside.
5. Launch Test Centric and click File -> Open... and select test assembly file in the binary folder of the solution (TC executable is located in different place than test assembly)
6. Run created tests
7. See error

**Expected behavior**
No failure but successful result of the test since test should search for all files in binary folder but not the TC executable folder. 
The working directory should be changed to the binary assembly after loading the assembly.

**Screenshots**
-

**Environment (please complete the following information):**
 - TestCentric Version 2.0.0-apha6
 - OS: Windows 10
 - Target Runtime for your test assembly: .NET Framework 4.7.2

**Comment by CharliePoole** [comment]
Short answer:

This is not a bug but a decision made at the time NUnit 3 was developed. TestCentric adheres to the same decision in its design.

Longer answer:

There are actually three pieces of software involved here: the runner, the engine and the framework. The problem you are facing is actually a function of the framework rather than of TestCentric.

The NUnit 2 framework did, as you say, change the current directory to the directory containing the assembly when running each test assembly. This was a specific guarantee, which programmers could rely upon. With NUnit 3, this was changed for two reasons:

1. It was generally thought to be a bad practice for an executing program to change the current directory because the cd is something that applies to the entire process, not just the running tests.

2. NUnit 3 Introduced the possibility of running several tests in parallel, which would make maintaining the proper cd for each assembly a more difficult chore.

NUnit 3 replaced the old guarantee that the current directory would be set to the directory containing the test assembly with a new facility allowing the creator of the tests the ability to easily _determine_ the path to that directory by use of `TestContext.CurrentContext.TestDirectory`. To access files in the same directory as your test assembly, you should construct the path using that property.

If your tests are being run correctly under the NUnit 3 console, then I suspect that the script launching the runner is changing the directory beforehand.

**Comment by gps7** [comment]
@CharliePoole thanks for clarification. I was suspecting this but now I have a clear answer. I also found an easy workaround for that use provided AppContext (using FW4.7.2):
`var path = AppContext.BaseDirectory + @"\subfolder\settings.xml"`
